packages:
  - "apps/cloud"
  - "apps/docs"
  - "benchmarks"
  - "examples"
  - "packages/*"
  - "tooling/*"
allowBuilds:
  esbuild: true
  msw: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  workerd: true
