/**
 * opencode hook emitter.
 *
 * Translates platform-agnostic hook modules into an opencode plugin at
 * `.opencode/plugin/memofs.ts` (opencode auto-loads plugin files from that
 * directory; verified against opencode.ai/docs/plugins, July 2026). The
 * plugin receives `{ $, client }` and subscribes to bus events via the
 * generic `event` hook.
 *
 * Capability honesty: opencode plugin event handlers are fire-and-forget
 * observers — there is no supported way to inject text into the model's
 * context from `session.created`, and no subagent-start or pre-compaction
 * injection point. So `contextInjection: false`: the plugin runs side
 * effects (cloud pull, session-start marker for `memofs status` compliance,
 * status toast on idle), while the generated rules file keeps the
 * "call `memofs.context` yourself" phrasing (`hooksInstalled` stays false).
 *
 * @module opencode
 */

import type { HookCapabilities, HookEmitter, HookModule } from "./types";

const OPENCODE_CAPABILITIES: HookCapabilities = {
	sessionStart: true,
	subagentStart: false,
	preCompact: false,
	stop: true,
	contextInjection: false,
	stopOutputMethod: "toast",
};

function buildPluginContent(modules: readonly HookModule[]): string {
	const hasSessionStart = modules.some(
		(m) =>
			m.event === "sessionStart" &&
			m.requires.every((r) => OPENCODE_CAPABILITIES[r]),
	);
	const hasStop = modules.some(
		(m) =>
			m.event === "stop" && m.requires.every((r) => OPENCODE_CAPABILITIES[r]),
	);

	const lines: string[] = [
		"/**",
		" * MemoFS opencode plugin — generated by `memofs generate`.",
		" *",
		" * - session.created: pulls cloud memory (when MEMOFS_API_KEY is set) and",
		" *   writes the session-start marker used by `memofs status` compliance.",
		" * - session.idle: shows the MemoFS compliance summary as a toast.",
		" *",
		" * opencode cannot inject context automatically — the agent loads memory",
		" * itself via the memofs MCP tools (see AGENTS.md).",
		" */",
		'import type { Plugin } from "@opencode-ai/plugin";',
		"",
		"export const MemofsPlugin: Plugin = async ({ $, client }) => {",
		"\treturn {",
		"\t\tevent: async ({ event }) => {",
	];

	if (hasSessionStart) {
		lines.push(
			'\t\t\tif (event.type === "session.created") {',
			"\t\t\t\tif (process.env.MEMOFS_API_KEY) {",
			"\t\t\t\t\tawait $`memofs cloud sync pull`.quiet().nothrow();",
			"\t\t\t\t}",
			"\t\t\t\t// Session boundary marker for `memofs status` compliance checks.",
			'\t\t\t\tawait $`memofs context --query "project context" --task-type general --mark-session-start`',
			"\t\t\t\t\t.quiet()",
			"\t\t\t\t\t.nothrow();",
			"\t\t\t}",
		);
	}
	if (hasStop) {
		lines.push(
			'\t\t\tif (event.type === "session.idle") {',
			"\t\t\t\tconst status = await $`memofs status`.quiet().nothrow().text();",
			"\t\t\t\tawait client.tui",
			"\t\t\t\t\t.showToast({",
			'\t\t\t\t\t\tbody: { message: status.trim().slice(0, 500), variant: "info" },',
			"\t\t\t\t\t})",
			"\t\t\t\t\t.catch(() => {});",
			"\t\t\t}",
		);
	}

	lines.push("\t\t},", "\t};", "};", "");
	return lines.join("\n");
}

export const opencodeEmitter: HookEmitter = {
	target: "opencode",
	capabilities: OPENCODE_CAPABILITIES,
	emitHooks(modules, _contextOverride) {
		const supportedModules = modules.filter((m) =>
			m.requires.every((r) => OPENCODE_CAPABILITIES[r]),
		);
		const content = buildPluginContent(supportedModules);
		return [{ path: ".opencode/plugin/memofs.ts", content }];
	},
};
