/**
 * Ambient type declarations for Cloudflare Worker secrets.
 *
 * These secrets are set via `wrangler secret put <NAME>` and are NOT declared
 * in `wrangler.toml` (which would expose them in version control). The
 * auto-generated `worker-configuration.d.ts` only includes bindings from
 * `wrangler.toml`; this file augments the global `Env` interface and the
 * `cloudflare:workers` module so that `import { env } from "cloudflare:workers"`
 * resolves to a type that includes every secret.
 *
 * @see worker-configuration.d.ts — auto-generated by `wrangler types`
 */
interface Env {
	DATABASE_URL: string;
	DATABASE_AUTH_TOKEN: string;
	API_KEY_SALT: string;
	ENCRYPTION_KEY: string;
	SESSION_SECRET: string;
	BETTER_AUTH_SECRET: string;
	VOYAGE_API_KEY: string;
	R2_S3_ACCESS_KEY_ID: string;
	R2_S3_SECRET_ACCESS_KEY: string;
	R2_S3_ENDPOINT: string;
	R2_BUCKET_NAME: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	CLOUD_PUBLIC_BASE_URL: string;
	POLAR_WEBHOOK_SECRET: string;
	POLAR_ACCESS_TOKEN: string;
	RESEND_API_KEY: string;
}

declare module "cloudflare:workers" {
	export const env: Env;
}
